server:
  port: 8002
spring:
  application:
    name: consume-application
eureka:
  client:
    # false表示eureka不向注册中心注册自己
    register-with-eureka: true
    # false表示只需要维护实例，不需要检索实例
    fetch-registry: true
    # 单机版
    # 集群版
    #defaultZone: http://ip1:7001/eureka,http://ip2:7001/eureka
    service-url:
       defaultZone: http://localhost:7001/eureka
  instance:
    # 客户端向服务端发送心跳的时间，默认30s
    lease-expiration-duration-in-seconds: 30
    # 服务端收到最后一次心跳后等待下一次时间的上限时间(默认90s)，超时剔除服务
    lease-renewal-interval-in-seconds: 90
